# Generated by Django 5.2.7 on 2025-10-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='home_team',
            new_name='team1',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='away_team',
            new_name='team2',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='home_goals',
            new_name='team1_goals',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='away_goals',
            new_name='team2_goals',
        ),
        migrations.AlterField(
            model_name='fixture',
            name='venue',
            field=models.CharField(default='Main Stadium', max_length=200),
        ),
    ]
