# Generated by Django 5.2.7 on 2025-10-03 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20251003_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='assist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists_made', to='matches.player'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_fixtures', to='matches.club'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_fixtures', to='matches.club'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_scored', to='matches.player'),
        ),
    ]
